# Generated by Django 3.2.4 on 2021-08-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400)),
                ('number', models.IntegerField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
            ],
        ),
    ]
